# Generated by Django 5.2.16 on 2026-08-05 19:28

import utilities.folder_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='acknowledgement_jpg',
            field=models.FileField(blank=True, null=True, upload_to=utilities.folder_manager.get_acknowledgement_path),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='acknowledgement_pdf',
            field=models.FileField(blank=True, null=True, upload_to=utilities.folder_manager.get_acknowledgement_path),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='acknowledgement_png',
            field=models.FileField(blank=True, null=True, upload_to=utilities.folder_manager.get_acknowledgement_path),
        ),
    ]
