# Generated by Django 5.2.16 on 2026-08-06 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0006_studentapplication_storage_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='jpeg_quality',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='validation_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
