# Generated by Django 6.0.8 on 2026-08-07 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_trainingpartner_batchcode'),
        ('registrations', '0009_studentapplication_annual_income_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='program_opting',
        ),
        migrations.RemoveField(
            model_name='studentapplication',
            name='year_of_study',
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='applying_qualification',
            field=models.CharField(choices=[('10th Pass (SSC)', '10th Pass (SSC)'), ('Intermediate (10+2)', 'Intermediate (10+2)'), ('ITI', 'ITI'), ('Polytechnic Diploma', 'Polytechnic Diploma'), ('Diploma in Engineering', 'Diploma in Engineering'), ('Pursuing Diploma', 'Pursuing Diploma'), ('Completed Diploma', 'Completed Diploma'), ('Pursuing 1st Year of UG', 'Pursuing 1st Year of UG'), ('Pursuing 2nd Year of UG', 'Pursuing 2nd Year of UG'), ('Pursuing 3rd Year of UG', 'Pursuing 3rd Year of UG'), ('Pursuing 4th Year of UG', 'Pursuing 4th Year of UG'), ('BA', 'BA'), ('B.Com', 'B.Com'), ('B.Sc', 'B.Sc'), ('BCA', 'BCA'), ('BBA', 'BBA'), ('B.Tech / BE', 'B.Tech / BE'), ('MBBS', 'MBBS'), ('BDS', 'BDS'), ('B.Pharmacy', 'B.Pharmacy'), ('B.Ed', 'B.Ed'), ('LLB', 'LLB'), ('MCA', 'MCA'), ('MBA', 'MBA'), ('M.Tech / ME', 'M.Tech / ME'), ('M.Sc', 'M.Sc'), ('M.Com', 'M.Com'), ('MA', 'MA'), ('Ph.D', 'Ph.D'), ('Other', 'Other')], default='10th Pass (SSC)', max_length=50),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='batch_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='completion_status',
            field=models.CharField(choices=[('Ongoing', 'Ongoing'), ('Completed', 'Completed')], default='Completed', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='custom_stream',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='mode_of_qualification',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('Distance', 'Distance'), ('Online', 'Online')], default='Full Time', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='training_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.trainingpartner'),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='year_of_passing',
            field=models.IntegerField(default=2024),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='abc_id',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
