# Generated by Django 5.2.16 on 2026-08-07 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0010_remove_studentapplication_program_opting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='consent_given',
            field=models.BooleanField(default=False),
        ),
    ]
