from django.urls import path
from . import views
from . import form_builder_views

urlpatterns = [
    path('', views.dashboard_home, name='dashboard_home'),

    # Form Builder
    path('form-builder/', form_builder_views.form_builder_home, name='form_builder'),
    path('form-builder/field/new/', form_builder_views.form_builder_edit, name='form_builder_new'),
    path('form-builder/field/<int:field_id>/edit/', form_builder_views.form_builder_edit, name='form_builder_edit'),
    path('form-builder/field/<int:field_id>/move/<str:direction>/', form_builder_views.form_builder_field_move, name='form_builder_field_move'),
    path('form-builder/bulk/', form_builder_views.form_builder_bulk, name='form_builder_bulk'),
    path('form-builder/preview/', form_builder_views.form_builder_preview, name='form_builder_preview'),
    path('form-builder/history/', form_builder_views.form_builder_history, name='form_builder_history'),
    path('form-builder/history/<int:version_id>/restore/', form_builder_views.form_builder_restore, name='form_builder_restore'),
    path('form-builder/section/<int:section_id>/save/', form_builder_views.form_builder_section_save, name='form_builder_section_save'),
    path('form-builder/option/<int:field_id>/add/', form_builder_views.form_builder_option_add, name='form_builder_option_add'),
    path('form-builder/option/<int:option_id>/edit/', form_builder_views.form_builder_option_edit, name='form_builder_option_edit'),
    path('form-builder/option/<int:option_id>/delete/', form_builder_views.form_builder_option_delete, name='form_builder_option_delete'),
    path('form-builder/option/<int:option_id>/move/<str:direction>/', form_builder_views.form_builder_option_move, name='form_builder_option_move'),
    path('form-builder/api/rules/', form_builder_views.form_builder_rules_json, name='form_builder_rules_json'),
    
    # Placeholder URLs for Sidebar
    path('applications/', views.application_list, name='application_list'),
    path('applications/new/', views.application_new, name='application_new'),
    path('applications/pending/', views.application_pending, name='application_pending'),
    path('students/', views.student_directory, name='student_directory'),
    path('students/<int:app_id>/profile/', views.student_profile, name='student_profile'),
    path('students/advanced-search/', views.student_advanced_search, name='student_advanced_search'),
    path('students/advanced-search/export/', views.advanced_search_export, name='advanced_search_export'),
    path('students/bulk-operations/', views.student_bulk_operations, name='student_bulk_operations'),
    path('students/bulk-operations/export/csv/', views.bulk_export_csv, name='bulk_export_csv'),
    path('students/bulk-operations/export/excel/', views.bulk_export_excel, name='bulk_export_excel'),
    path('students/bulk-operations/download/documents/', views.bulk_download_documents, name='bulk_ops_download_documents'),
    path('students/bulk-operations/download/applications/', views.bulk_download_applications, name='bulk_ops_download_applications'),
    path('students/bulk-operations/change-status/', views.bulk_change_status, name='bulk_ops_change_status'),
    path('students/bulk-operations/assign-training-partner/', views.bulk_assign_training_partner, name='bulk_ops_assign_training_partner'),
    path('students/bulk-operations/assign-batch-code/', views.bulk_assign_batch_code, name='bulk_ops_assign_batch_code'),
    path('students/bulk-operations/request-correction/', views.bulk_request_correction, name='bulk_request_correction'),
    path('students/bulk-operations/send-email/', views.bulk_notify, name='bulk_send_email'),
    path('students/bulk-change-status/', views.bulk_change_status, name='bulk_change_status'),
    path('students/bulk-assign-training-partner/', views.bulk_assign_training_partner, name='bulk_assign_training_partner'),
    path('students/bulk-assign-batch/', views.bulk_assign_batch_code, name='bulk_assign_batch_code'),
    path('students/bulk-download-applications/', views.bulk_download_applications, name='bulk_download_applications'),
    path('students/bulk-notify/', views.bulk_notify, name='bulk_notify'),
    path('students/bulk-print/', views.bulk_print, name='bulk_print'),
    path('verification/', views.verification_desk, name='verification_desk'),
    path('reports/', views.reports_dashboard, name='reports_dashboard'),
    path('reports/daily/', views.report_daily, name='report_daily'),
    path('reports/daily/export/', views.report_daily_export, name='report_daily_export'),
    path('reports/demographics/', views.report_demographics, name='report_demographics'),
    path('reports/demographics/export/', views.report_demographics_export, name='report_demographics_export'),
    path('reports/geographical/', views.report_geographical, name='report_geographical'),
    path('reports/geographical/export/', views.report_geographical_export, name='report_geographical_export'),
    path('exports/', views.export_center, name='export_center'),
    path('exports/generate/', views.export_center_generate, name='export_center_generate'),
    path('exports/download/<int:job_id>/', views.export_center_download, name='export_center_download'),
    path('master-data/', views.master_data, name='master_data'),
    path('settings/', views.settings_dashboard, name='settings_dashboard'),
    path('backup/', views.backup_center, name='backup_center'),
    path('backup/create/', views.backup_create, name='backup_create'),
    path('backup/download/<int:job_id>/', views.backup_download, name='backup_download'),
    path('backup/restore/', views.backup_restore, name='backup_restore'),
    path('backup/restore/execute/', views.backup_restore_execute, name='backup_restore_execute'),
    path('audit-logs/', views.audit_logs, name='audit_logs'),
    
    # Export Endpoints
    path('export/csv/', views.export_csv, name='export_csv'),
    path('export/db/', views.export_db, name='export_db'),
    
    # Bulk Action Endpoints (POST)
    path('applications/bulk-export/', views.bulk_export, name='bulk_export'),
    path('applications/bulk-download-documents/', views.bulk_download_documents, name='bulk_download_documents'),
    path('applications/bulk-correction/', views.bulk_correction, name='bulk_correction'),
    path('applications/bulk-verify/', views.bulk_verify, name='bulk_verify'),
]
