# Generated by Django 5.2.16 on 2026-08-14 19:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_type', models.CharField(choices=[('applications', 'Student Applications'), ('students', 'Student Directory'), ('documents', 'Documents'), ('reports', 'Application Reports'), ('master_data', 'Master Data'), ('audit_logs', 'Audit Logs')], max_length=50)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel'), ('pdf', 'PDF'), ('zip', 'ZIP')], max_length=20)),
                ('filters', models.JSONField(blank=True, default=dict)),
                ('record_count', models.PositiveIntegerField(default=0)),
                ('file', models.FileField(blank=True, null=True, upload_to='exports/')),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'permissions': [('view_export_center', 'Can view the Export Center'), ('export_applications', 'Can export applications'), ('export_student_data', 'Can export student data'), ('export_documents', 'Can export documents'), ('export_master_data', 'Can export master data'), ('export_audit_logs', 'Can export audit logs'), ('download_export_history', 'Can download export history')],
            },
        ),
    ]
