# Generated by Django 6.0.8 on 2026-08-15 03:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_backupjob_systemsetting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portal_name', models.CharField(blank=True, default='CSC Admin Portal', max_length=255)),
                ('organization_name', models.CharField(blank=True, default='Council for Skills and Competencies', max_length=255)),
                ('contact_email', models.EmailField(blank=True, default='', max_length=255)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('support_email', models.EmailField(blank=True, default='', max_length=255)),
                ('support_phone', models.CharField(blank=True, default='', max_length=30)),
                ('logo', models.FileField(blank=True, null=True, upload_to='platform/logo/')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='platform/favicon/')),
                ('portal_description', models.TextField(blank=True, default='')),
                ('timezone', models.CharField(blank=True, default='UTC', max_length=100)),
                ('date_format', models.CharField(blank=True, default='d M Y', max_length=50)),
                ('maintenance_mode', models.BooleanField(default=False)),
                ('auto_save_enabled', models.BooleanField(default=True)),
                ('auto_save_interval', models.PositiveIntegerField(default=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='platform_setting_updates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('view_platform_settings', 'Can view Platform Settings'), ('change_platform_settings', 'Can change Platform Settings')],
            },
        ),
    ]
