# Generated by Django 6.0.8 on 2026-08-15 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_seed_platform_setting'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('icon', models.CharField(blank=True, default='view_module', max_length=60)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='FormConfigurationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('label', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='published', max_length=20)),
                ('changes', models.TextField(blank=True, default='')),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_config_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='FormFieldConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Textarea'), ('email', 'Email'), ('number', 'Number'), ('date', 'Date'), ('select', 'Dropdown'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('file', 'File Upload'), ('phone', 'Phone'), ('aadhaar', 'Aadhaar'), ('pincode', 'Pincode')], default='text', max_length=20)),
                ('placeholder', models.CharField(blank=True, default='', max_length=255)),
                ('help_text', models.TextField(blank=True, default='')),
                ('required', models.BooleanField(default=False)),
                ('visible', models.BooleanField(default=True)),
                ('readonly', models.BooleanField(default=False)),
                ('default_value', models.TextField(blank=True, default='')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True)),
                ('max_length', models.PositiveIntegerField(blank=True, null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('regex_pattern', models.CharField(blank=True, default='', max_length=500)),
                ('validator_type', models.CharField(blank=True, default='', max_length=30)),
                ('options_source', models.CharField(choices=[('options', 'Configured Options'), ('masterdata', 'Master Data Table')], default='options', max_length=20)),
                ('source_model', models.CharField(blank=True, default='', max_length=100)),
                ('options', models.JSONField(blank=True, default=list)),
                ('allowed_file_types', models.JSONField(blank=True, default=list)),
                ('max_file_size', models.PositiveIntegerField(blank=True, help_text='Maximum file size in KB', null=True)),
                ('min_file_size', models.PositiveIntegerField(blank=True, help_text='Minimum file size in KB', null=True)),
                ('image_min_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_min_height', models.PositiveIntegerField(blank=True, null=True)),
                ('validation_messages', models.JSONField(blank=True, default=dict)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_conditional', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_field_updates', to=settings.AUTH_USER_MODEL)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fields', to='dashboard.formsection')),
            ],
            options={
                'ordering': ['section__display_order', 'display_order', 'id'],
                'permissions': [('view_form_builder', 'Can view Form Builder'), ('change_form_builder', 'Can change form configuration')],
            },
        ),
        migrations.CreateModel(
            name='FormFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_options', to='dashboard.formfieldconfiguration')),
            ],
            options={
                'ordering': ['display_order', 'id'],
            },
        ),
    ]
