# Generated by Django 5.2.16 on 2026-08-05 19:05

import django.db.models.deletion
import utilities.folder_manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masterdata', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('father_name', models.CharField(max_length=150)),
                ('mother_name', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('mobile_number', models.CharField(max_length=10, unique=True)),
                ('alternative_mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('communication_address', models.TextField()),
                ('pincode', models.CharField(max_length=6)),
                ('institution', models.CharField(max_length=200)),
                ('hall_ticket_number', models.CharField(max_length=50)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('aadhaar_number', models.CharField(max_length=12, unique=True)),
                ('abc_id', models.CharField(max_length=50, unique=True)),
                ('distinguishing_mark', models.CharField(max_length=255)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('browser_info', models.TextField(blank=True, null=True)),
                ('community', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.community')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.country')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.district')),
                ('ex_serviceman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.exservicestatus')),
                ('marital_status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.maritalstatus')),
                ('occupation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.occupation')),
                ('program_opting', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.program')),
                ('qualification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.qualification')),
                ('religion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.religion')),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.state')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.applicationstatus')),
                ('year_of_study', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='masterdata.yearofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=50)),
                ('original_file', models.FileField(upload_to=utilities.folder_manager.get_upload_path)),
                ('compressed_file', models.FileField(blank=True, null=True, upload_to=utilities.folder_manager.get_upload_path)),
                ('original_file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('optimized_file_size', models.PositiveIntegerField(blank=True, help_text='Size in bytes', null=True)),
                ('image_width', models.PositiveIntegerField(blank=True, null=True)),
                ('image_height', models.PositiveIntegerField(blank=True, null=True)),
                ('mime_type', models.CharField(blank=True, max_length=100, null=True)),
                ('compression_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='registrations.studentapplication')),
            ],
        ),
    ]
