# Generated by Django 5.2.16 on 2026-08-06 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0003_country_iso_code'),
        ('registrations', '0003_studentapplication_approval_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.community'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.country'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.district'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='ex_serviceman',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.exservicestatus'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='marital_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.maritalstatus'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='occupation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.occupation'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='program_opting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.program'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.qualification'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='religion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.religion'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.state'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='year_of_study',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='masterdata.yearofstudy'),
        ),
    ]
