# Generated by Django 5.2.16 on 2026-08-06 04:38

import registrations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0004_alter_studentapplication_community_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='aadhaar_number',
            field=models.CharField(max_length=12, unique=True, validators=[registrations.validators.validate_aadhaar]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='alternative_mobile',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[registrations.validators.validate_indian_mobile]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='father_name',
            field=models.CharField(max_length=150, validators=[registrations.validators.validate_person_name]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='full_name',
            field=models.CharField(max_length=150, validators=[registrations.validators.validate_person_name]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='hall_ticket_number',
            field=models.CharField(max_length=50, validators=[registrations.validators.validate_hall_ticket]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='mobile_number',
            field=models.CharField(max_length=10, unique=True, validators=[registrations.validators.validate_indian_mobile]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='mother_name',
            field=models.CharField(max_length=150, validators=[registrations.validators.validate_person_name]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='pincode',
            field=models.CharField(max_length=6, validators=[registrations.validators.validate_indian_pincode]),
        ),
    ]
