# Generated by Django 5.2.16 on 2026-08-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0005_alter_studentapplication_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='storage_folder',
            field=models.CharField(blank=True, help_text='Stable media folder name based on Aadhaar and Name', max_length=255, null=True),
        ),
    ]
