# Generated by Django 5.2.16 on 2026-08-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0007_uploadeddocument_jpeg_quality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='processing_policy',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
