# Generated by Django 5.2.16 on 2026-08-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0008_uploadeddocument_processing_policy'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='annual_income',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='category',
            field=models.CharField(choices=[('OC (General)', 'OC (General)'), ('EWS', 'EWS'), ('BC-A', 'BC-A'), ('BC-B', 'BC-B'), ('BC-C', 'BC-C'), ('BC-D', 'BC-D'), ('BC-E', 'BC-E'), ('SC', 'SC'), ('ST', 'ST')], default='OC (General)', max_length=20),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='nationality',
            field=models.CharField(choices=[('Indian', 'Indian'), ('Other', 'Other')], default='Indian', max_length=50),
        ),
        migrations.AddField(
            model_name='studentapplication',
            name='physically_handicapped',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10),
        ),
    ]
