# Generated by Django 5.2.16 on 2026-08-09 18:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_trainingpartner_batchcode'),
        ('registrations', '0011_studentapplication_consent_given'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='program_opting',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.program'),
        ),
    ]
