# Generated by Django 5.2.16 on 2026-08-09 18:32

import django.db.models.deletion
import registrations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0004_trainingpartner_batchcode'),
        ('registrations', '0012_studentapplication_program_opting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True, validators=[registrations.validators.validate_aadhaar]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='abc_id',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='annual_income',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='category',
            field=models.CharField(blank=True, choices=[('OC (General)', 'OC (General)'), ('EWS', 'EWS'), ('BC-A', 'BC-A'), ('BC-B', 'BC-B'), ('BC-C', 'BC-C'), ('BC-D', 'BC-D'), ('BC-E', 'BC-E'), ('SC', 'SC'), ('ST', 'ST')], default='OC (General)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.community'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.country'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='distinguishing_mark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='district',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.district'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='ex_serviceman',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.exservicestatus'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='father_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[registrations.validators.validate_person_name]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='full_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[registrations.validators.validate_person_name]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='hall_ticket_number',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[registrations.validators.validate_hall_ticket]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='institution',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='marital_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.maritalstatus'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, validators=[registrations.validators.validate_indian_mobile]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[registrations.validators.validate_person_name]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='nationality',
            field=models.CharField(blank=True, choices=[('Indian', 'Indian'), ('Other', 'Other')], default='Indian', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='occupation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.occupation'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='physically_handicapped',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='pincode',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[registrations.validators.validate_indian_pincode]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='qualification',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.qualification'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='religion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.religion'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='masterdata.state'),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='year_of_passing',
            field=models.IntegerField(blank=True, default=2024, null=True),
        ),
    ]
