# Generated by Django 6.0.8 on 2026-08-12 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0013_alter_studentapplication_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentapplication',
            name='category',
        ),
    ]
