# Generated by Django 4.2.22 on 2026-08-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0014_remove_studentapplication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='area_village_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
