# Generated by Django 5.2.16 on 2026-08-14 13:03

import registrations.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0016_alter_studentapplication_applying_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentapplication',
            name='aadhaar_number',
            field=models.CharField(blank=True, max_length=12, null=True, validators=[registrations.validators.validate_aadhaar]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='abc_id',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='applying_qualification',
            field=models.CharField(choices=[('12th or equivalent', '12th or equivalent'), ('2yrs of 3 yr dip in ECE/EE/CS/IT and allied branches after 10th', '2yrs of 3 yr dip in ECE/EE/CS/IT and allied branches after 10th'), ('Previous relevant Qualification of NSQF Level 3', 'Previous relevant Qualification of NSQF Level 3'), ('Previous relevant Qualification of NSQF Level 5', 'Previous relevant Qualification of NSQF Level 5'), ('Pursing 3rd yr of UG in CS/IT /ECE/EE/allied branches', 'Pursing 3rd yr of UG in CS/IT /ECE/EE/allied branches'), ('Completed 3 year of UG in CS/IT/ECE/EE/allied branches', 'Completed 3 year of UG in CS/IT/ECE/EE/allied branches')], default='12th or equivalent', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[registrations.validators.validate_indian_mobile]),
        ),
        migrations.AlterField(
            model_name='studentapplication',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
