# Generated by Django 6.0.8 on 2026-08-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0017_alter_studentapplication_aadhaar_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentapplication',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Archived applications are kept but hidden from routine workflow.'),
        ),
    ]
