# Generated by Django 5.2.16 on 2026-08-05 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('masterdata', '0002_verificationstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True),
        ),
    ]
